version: "3.9"

services:
  backend:
    build: 
      context: .
    restart: always
    command: uwsgi --socket 0.0.0.0:9000 --workers 4 --master --enable-threads --module rtltools.wsgi
    ports:
      - "9000:9000"
    volumes:
      - .:/printer_app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7.0-alpine

  celery:
    build: 
      context: .
    volumes:
      - .:/printer_app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

  nginx:
    build: 
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - APP_HOST=backend
      - APP_PORT=9000
      - LISTEN_PORT=80
    depends_on:
      - backend
    links:
      - backend

volumes:
  postgres_data: