# Generated by Django 4.2.6 on 2023-10-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер кабинета')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='printer_tool.address')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='Производитель')),
                ('model', models.CharField(max_length=100, verbose_name='Модель принтера')),
                ('local_name', models.CharField(max_length=100, verbose_name='Локальное имя принтера')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='printer_tool.cabinet')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.BooleanField(blank=True, default=False, verbose_name='Оригинальный картридж')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип картриджа')),
                ('model', models.CharField(max_length=20, verbose_name='Модель картриджа')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('printer', models.ManyToManyField(related_name='cartridges', to='printer_tool.printer')),
            ],
            options={
                'verbose_name': 'Картридж',
                'verbose_name_plural': 'Картриджи',
                'abstract': False,
            },
        ),
    ]
