# Generated by Django 4.2.6 on 2023-10-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_tool', '0002_printer_toner_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=15, verbose_name='Сетевой адрес принтера'),
        ),
    ]
