# Generated by Django 4.2.6 on 2023-11-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_tool', '0003_printer_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Сетевой адрес принтера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Локальное имя принтера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='toner_level',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Уровень тонера'),
        ),
    ]
